"use client"

import Image from "next/image"
import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { Building2, Check, ChevronLeft, ChevronRight, FileImage, GraduationCap, Tags } from "lucide-react"
import { sileo } from "sileo"
import { ReclutadorShell } from "@/components/reclutador-shell"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { authHeader, clearSession, getSession } from "@/lib/session"
import type { AuthResponse } from "@/types/auth"
import type { AvisoFormularioSoporte, ReclutadorActual } from "@/types/aviso-form"

const pasos=["Empresa","Información","Carreras","Clasificación","Revisión"]

export default function NuevoAvisoPage(){
 const router=useRouter(),[session,setSession]=useState<AuthResponse|null>(null),[reclutador,setReclutador]=useState<ReclutadorActual|null>(null),[soporte,setSoporte]=useState<AvisoFormularioSoporte|null>(null),[paso,setPaso]=useState(0),[enviando,setEnviando]=useState(false)
 const [empresaId,setEmpresaId]=useState(""),[nombre,setNombre]=useState(""),[descripcion,setDescripcion]=useState(""),[fechaCierre,setFechaCierre]=useState(""),[imagen,setImagen]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[carreras,setCarreras]=useState<Record<number,number>>({}),[tipos,setTipos]=useState<Record<number,number[]>>({})
 const [buscarCarrera,setBuscarCarrera]=useState("")
 useEffect(()=>{const s=getSession();if(!s||!s.roles.some(r=>r.toUpperCase()==="RECLUTADOR")){router.replace("/login");return}setSession(s);fetch("/api/pala/reclutador/me",{headers:authHeader(s),cache:"no-store"}).then(async r=>{if(r.status===401){clearSession();router.replace("/login");throw new Error("Sesión vencida")}const b=await r.json();if(!r.ok)throw new Error(b.mensaje);setReclutador(b);return fetch(`/api/pala/reclutadores/${b.id}/avisos/soporte`,{headers:authHeader(s),cache:"no-store"})}).then(async r=>{if(!r)return;const b=await r.json();if(!r.ok)throw new Error(b.mensaje);setSoporte(b)}).catch(e=>sileo.error({title:"No se pudo preparar el formulario",description:e.message}))},[router])
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview])
 const empresa=soporte?.empresasActivas.find(e=>String(e.id)===empresaId),seleccionCarreras=Object.keys(carreras).map(Number),seleccionTipos=Object.entries(tipos).filter(([,subs])=>subs.length>0)
 const puedePublicar=session?.permisos.includes("PUBLICAR_AVISO")??false,puedeCrear=session?.permisos.includes("CREAR_AVISO")??false
 const valido=useMemo(()=>{if(paso===0)return Boolean(empresaId);if(paso===1)return nombre.trim().length>=4&&descripcion.trim().length>=20&&Boolean(fechaCierre)&&new Date(fechaCierre)>new Date();if(paso===2)return seleccionCarreras.length>0;if(paso===3)return seleccionTipos.length>0;return true},[paso,empresaId,nombre,descripcion,fechaCierre,seleccionCarreras.length,seleccionTipos.length])
 function elegirImagen(file:File|null){if(!file){setImagen(null);setPreview(null);return}if(!["image/jpeg","image/png","image/webp"].includes(file.type)){sileo.error({title:"Formato no permitido",description:"Usá JPG, PNG o WebP."});return}if(file.size>5*1024*1024){sileo.error({title:"Imagen demasiado grande",description:"El máximo es 5 MB."});return}setImagen(file);setPreview(URL.createObjectURL(file))}
 function toggleCarrera(id:number){setCarreras(v=>{const n={...v};if(n[id])delete n[id];else n[id]=Object.keys(n).length+1;return n})}
 function toggleSub(tipo:number,sub:number){setTipos(v=>{const actuales=v[tipo]??[],n=actuales.includes(sub)?actuales.filter(x=>x!==sub):[...actuales,sub];return{...v,[tipo]:n}})}
 async function enviar(borrador:boolean){if(!session||!reclutador||!puedeCrear)return;sileo.promise((async()=>{setEnviando(true);const datos={nombreAviso:nombre.trim(),descripcionAviso:descripcion.trim(),fechaPublicacionAviso:null,fechaCierreAviso:new Date(`${fechaCierre}T23:59:59`).toISOString(),imagenUrlAviso:null,empresaId:Number(empresaId),guardarComoBorrador:borrador,carreras:seleccionCarreras.map(id=>({carreraId:id,prioridad:carreras[id]})),tiposAviso:seleccionTipos.map(([id,subs])=>({tipoAvisoId:Number(id),subTipoAvisoIds:subs}))};const form=new FormData();form.append("datos",new Blob([JSON.stringify(datos)],{type:"application/json"}));if(imagen)form.append("imagen",imagen);const r=await fetch(`/api/pala/reclutadores/${reclutador.id}/avisos`,{method:"POST",headers:authHeader(session),body:form}),b=await r.json();if(!r.ok)throw new Error(b.mensaje??"No se pudo crear el aviso");router.push("/reclutador");return b})().finally(()=>setEnviando(false)),{loading:{title:borrador?"Guardando borrador...":"Publicando aviso..."},success:{title:borrador?"Borrador guardado":"Aviso publicado"},error:{title:"No se pudo crear el aviso"}})}
 if(!session)return null
 return <ReclutadorShell mail={session.mailUsuario}><header className="mb-7"><p className="text-sm font-medium text-sky-600">Nuevo aviso</p><h1 className="mt-1 text-3xl font-semibold">Crear oportunidad laboral</h1><p className="mt-2 text-sm text-slate-500">Completá cada paso y revisá el resultado antes de publicar.</p></header>
 <div className="mb-7 grid grid-cols-5 gap-2">{pasos.map((p,i)=><div key={p}><div className={`h-1.5 rounded-full ${i<=paso?"bg-sky-600":"bg-slate-200"}`}/><p className={`mt-2 hidden text-xs sm:block ${i===paso?"font-semibold text-sky-700":"text-slate-500"}`}>{i+1}. {p}</p></div>)}</div>
 {!puedeCrear&&<p className="mb-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-800">Tu rol no tiene el permiso CREAR_AVISO.</p>}
 <Card className="border-0 shadow-sm"><CardHeader><CardTitle>{pasos[paso]}</CardTitle></CardHeader><CardContent className="min-h-[390px]">
 {paso===0&&<div>{!soporte?<p className="text-sm text-slate-500">Cargando empresas...</p>:soporte.empresasActivas.length===0?<div className="rounded-xl border border-dashed p-10 text-center"><Building2 className="mx-auto h-10 w-10 text-slate-400"/><p className="mt-4 font-medium">No tenés empresas asociadas</p><p className="mt-2 text-sm text-slate-500">Solicitá una asociación antes de crear avisos.</p><Button className="mt-5" onClick={()=>router.push("/solicitar-asociacion")}>Solicitar asociación</Button></div>:<div className="grid gap-3 md:grid-cols-2">{soporte.empresasActivas.map(e=><button key={e.id} onClick={()=>setEmpresaId(String(e.id))} className={`rounded-xl border p-5 text-left ${empresaId===String(e.id)?"border-sky-500 bg-sky-50 ring-2 ring-sky-100":"hover:border-slate-300"}`}><div className="flex justify-between"><b>{e.razonSocialEmpresa}</b>{empresaId===String(e.id)&&<Check className="h-5 w-5 text-sky-600"/>}</div><p className="mt-2 text-sm text-slate-500">CUIT {e.cuitEmpresa}</p></button>)}</div>}</div>}
 {paso===1&&<div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-5"><div><Label>Título</Label><Input className="mt-2" maxLength={140} value={nombre} onChange={e=>setNombre(e.target.value)} placeholder="Ej. Desarrollador/a Java Junior"/><p className="mt-1 text-right text-xs text-slate-400">{nombre.length}/140</p></div><div><Label>Descripción</Label><Textarea className="mt-2 min-h-36" maxLength={4000} value={descripcion} onChange={e=>setDescripcion(e.target.value)} placeholder="Responsabilidades, requisitos y beneficios..."/><p className="mt-1 text-right text-xs text-slate-400">{descripcion.length}/4000</p></div><div><Label>Fecha de cierre</Label><Input className="mt-2 max-w-xs" type="date" value={fechaCierre} onChange={e=>setFechaCierre(e.target.value)}/></div></div><div><Label>Imagen opcional</Label><label className="mt-2 grid min-h-56 cursor-pointer place-items-center overflow-hidden rounded-xl border-2 border-dashed bg-slate-50 text-center hover:border-sky-400">{preview?<Image src={preview} alt="Vista previa" width={640} height={360} unoptimized className="h-full w-full object-cover"/>:<span><FileImage className="mx-auto h-10 w-10 text-slate-400"/><span className="mt-3 block text-sm font-medium">Seleccionar imagen</span><span className="mt-1 block text-xs text-slate-500">JPG, PNG o WebP · máx. 5 MB</span></span>}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>elegirImagen(e.target.files?.[0]??null)}/></label>{imagen&&<Button className="mt-2" size="sm" variant="ghost" onClick={()=>elegirImagen(null)}>Quitar imagen</Button>}</div></div>}
 {paso===2&&<div><div className="relative mb-4"><GraduationCap className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input className="pl-9" placeholder="Buscar carrera" value={buscarCarrera} onChange={e=>setBuscarCarrera(e.target.value)}/></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{soporte?.carrerasActivas.filter(c=>c.nombreCarrera.toLowerCase().includes(buscarCarrera.trim().toLowerCase())).map(c=><button key={c.id} onClick={()=>toggleCarrera(c.id)} className={`flex min-h-12 items-center gap-3 rounded-lg border px-3 py-2.5 text-left ${carreras[c.id]?"border-sky-500 bg-sky-50 ring-1 ring-sky-100":"hover:bg-slate-50"}`}><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-md ${carreras[c.id]?"bg-sky-600 text-white":"bg-slate-100 text-slate-500"}`}>{carreras[c.id]?<Check className="h-4 w-4"/>:<GraduationCap className="h-3.5 w-3.5"/>}</span><span className="flex-1 text-sm font-medium">{c.nombreCarrera}</span>{carreras[c.id]&&<span className="text-xs font-semibold text-sky-700">#{carreras[c.id]}</span>}</button>)}</div><p className="mt-4 text-xs text-slate-500">{seleccionCarreras.length} carreras seleccionadas. El número indica la prioridad.</p></div>}
 {paso===3&&<div className="space-y-4">{soporte?.tiposAvisoActivos.map(t=><div key={t.id} className="rounded-xl border p-5"><div className="flex items-center gap-3"><Tags className="h-5 w-5 text-violet-600"/><div><b>{t.nombreTipoAviso}</b>{t.descripcionTipoAviso&&<p className="text-xs text-slate-500">{t.descripcionTipoAviso}</p>}</div></div><div className="mt-4 flex flex-wrap gap-2">{t.subTiposAviso.map(s=>{const on=(tipos[t.id]??[]).includes(s.id);return <button key={s.id} onClick={()=>toggleSub(t.id,s.id)} className={`rounded-full border px-3 py-2 text-sm ${on?"border-violet-500 bg-violet-50 text-violet-800":"hover:bg-slate-50"}`}>{on&&<Check className="mr-1 inline h-3.5 w-3.5"/>}{s.nombreSubTipoAviso}</button>})}</div></div>)}</div>}
 {paso===4&&<div className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-5"><Dato titulo="Empresa" valor={empresa?.razonSocialEmpresa}/><Dato titulo="Título" valor={nombre}/><Dato titulo="Descripción" valor={descripcion}/><Dato titulo="Fecha de cierre" valor={fechaCierre}/><Dato titulo="Carreras" valor={`${seleccionCarreras.length} seleccionadas`}/><Dato titulo="Clasificación" valor={`${seleccionTipos.length} tipos seleccionados`}/></div><div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{preview?<Image src={preview} alt="Imagen del aviso" width={640} height={360} unoptimized className="h-40 w-full object-cover"/>:<div className="grid h-40 place-items-center bg-slate-100"><FileImage className="h-10 w-10 text-slate-300"/></div>}<div className="p-5"><Badge className="bg-sky-100 text-sky-800">Vista previa</Badge><h3 className="mt-3 text-lg font-semibold">{nombre}</h3><p className="mt-2 line-clamp-3 text-sm text-slate-500">{descripcion}</p><p className="mt-4 text-xs font-medium text-slate-600">{empresa?.razonSocialEmpresa}</p></div></div></div>}
 </CardContent></Card>
 <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><Button variant="outline" disabled={paso===0} onClick={()=>setPaso(p=>p-1)}><ChevronLeft className="mr-1 h-4 w-4"/>Anterior</Button>{paso<4?<Button disabled={!valido} onClick={()=>setPaso(p=>p+1)}>Siguiente<ChevronRight className="ml-1 h-4 w-4"/></Button>:<div className="flex gap-2"><Button variant="outline" disabled={enviando||!puedeCrear} onClick={()=>enviar(true)}>Guardar borrador</Button><Button disabled={enviando||!puedeCrear||!puedePublicar} onClick={()=>enviar(false)}>Publicar aviso</Button></div>}</div>
 </ReclutadorShell>
}
function Dato({titulo,valor}:{titulo:string;valor?:string}){return <div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{titulo}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-700">{valor||"—"}</p></div>}
