"use client"

import Link from "next/link"
import { useCallback, useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { CalendarDays, CalendarRange, Eye, FilePlus2, MoreHorizontal, Pause, Play, Search, Users, XCircle } from "lucide-react"
import { sileo } from "sileo"
import { ReclutadorShell } from "@/components/reclutador-shell"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { authHeader, clearSession, getSession } from "@/lib/session"
import type { AuthResponse } from "@/types/auth"
import type { ReclutadorActual } from "@/types/aviso-form"
import type { AvisoGestion } from "@/types/aviso-gestion"

const formato=new Intl.DateTimeFormat("es-AR",{dateStyle:"medium"})
const tonos:Record<string,string>={BORRADOR:"bg-slate-200 text-slate-700",ABIERTO:"bg-emerald-100 text-emerald-800",PAUSADO:"bg-amber-100 text-amber-800",CANCELADO:"bg-rose-100 text-rose-800",CERRADO:"bg-violet-100 text-violet-800"}

export default function MisAvisosPage(){
 const router=useRouter(),[session,setSession]=useState<AuthResponse|null>(null),[reclutador,setReclutador]=useState<ReclutadorActual|null>(null),[avisos,setAvisos]=useState<AvisoGestion[]>([]),[busqueda,setBusqueda]=useState(""),[estado,setEstado]=useState("TODOS"),[fechaDesde,setFechaDesde]=useState(""),[fechaHasta,setFechaHasta]=useState(""),[vistaPrevia,setVistaPrevia]=useState<AvisoGestion|null>(null),[cancelar,setCancelar]=useState<AvisoGestion|null>(null),[cargando,setCargando]=useState(true),[error,setError]=useState("")
 const cargar=useCallback(async(s:AuthResponse,r:ReclutadorActual)=>{const response=await fetch(`/api/pala/reclutadores/${r.id}/avisos`,{headers:authHeader(s),cache:"no-store"});if(response.status===401){clearSession();router.replace("/login");return}const body=await response.json();if(!response.ok)throw new Error(body.mensaje??"No se pudieron cargar los avisos");setAvisos(body)},[router])
 useEffect(()=>{const s=getSession();if(!s||!s.roles.some(r=>r.toUpperCase()==="RECLUTADOR")){router.replace("/login");return}setSession(s);fetch("/api/pala/reclutador/me",{headers:authHeader(s),cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.mensaje);setReclutador(body);await cargar(s,body)}).catch(reason=>setError(reason.message)).finally(()=>setCargando(false))},[cargar,router])
 const filtrados=useMemo(()=>avisos.filter(a=>{const fecha=a.fechaCreacionAviso.slice(0,10);return(estado==="TODOS"||a.estadoActual.codigoInterno===estado)&&(!fechaDesde||fecha>=fechaDesde)&&(!fechaHasta||fecha<=fechaHasta)&&(!busqueda.trim()||`${a.nombreAviso} ${a.empresa.razonSocialEmpresa}`.toLowerCase().includes(busqueda.toLowerCase()))}),[avisos,estado,fechaDesde,fechaHasta,busqueda])
 const metricas=useMemo(()=>({total:avisos.length,activos:avisos.filter(a=>a.estadoActual.codigoInterno==="ABIERTO").length,postulaciones:avisos.reduce((total,a)=>total+(a.cantidadPostulaciones??0),0)}),[avisos])
 async function accion(aviso:AvisoGestion,nombre:"publicar"|"pausar"|"reanudar"|"cancelar"){if(!session||!reclutador)return;const response=await fetch(`/api/pala/reclutadores/${reclutador.id}/avisos/${aviso.id}/${nombre}`,{method:"PATCH",headers:authHeader(session)}),body=await response.json();if(!response.ok){sileo.error({title:"No se pudo actualizar el aviso",description:body.mensaje});return}sileo.success({title:nombre==="publicar"?"Aviso publicado":nombre==="pausar"?"Aviso pausado":nombre==="reanudar"?"Aviso reanudado":"Aviso cancelado"});setCancelar(null);await cargar(session,reclutador)}
 if(!session)return null
 return <ReclutadorShell mail={session.mailUsuario}><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-violet-600">Gestión de publicaciones</p><h1 className="mt-1 text-3xl font-semibold">Mis avisos</h1><p className="mt-2 text-sm text-slate-500">Consultá y controlá los avisos que creaste.</p></div><Button asChild><Link href="/reclutador/avisos/nuevo"><FilePlus2 className="mr-2 h-4 w-4"/>Nuevo aviso</Link></Button></header>
 {error&&<p className="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p>}
 <div className="mb-5 grid gap-3 sm:grid-cols-3"><Card className="shadow-none"><CardContent className="flex items-center gap-3 p-4"><FilePlus2 className="h-5 w-5 text-violet-600"/><div><p className="text-2xl font-semibold">{metricas.total}</p><p className="text-xs text-slate-500">Avisos creados</p></div></CardContent></Card><Card className="shadow-none"><CardContent className="flex items-center gap-3 p-4"><Play className="h-5 w-5 text-emerald-600"/><div><p className="text-2xl font-semibold">{metricas.activos}</p><p className="text-xs text-slate-500">Avisos abiertos</p></div></CardContent></Card><Card className="shadow-none"><CardContent className="flex items-center gap-3 p-4"><Users className="h-5 w-5 text-blue-600"/><div><p className="text-2xl font-semibold">{metricas.postulaciones}</p><p className="text-xs text-slate-500">Postulaciones recibidas</p></div></CardContent></Card></div>
 <div className="mb-5 grid gap-3 lg:grid-cols-[1fr_190px_170px_170px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input className="bg-white pl-9" placeholder="Buscar por título o empresa" value={busqueda} onChange={e=>setBusqueda(e.target.value)}/></div><Select value={estado} onValueChange={setEstado}><SelectTrigger className="bg-white"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="TODOS">Todos los estados</SelectItem>{["BORRADOR","ABIERTO","PAUSADO","CANCELADO","CERRADO"].map(e=><SelectItem key={e} value={e}>{e}</SelectItem>)}</SelectContent></Select><div className="relative"><CalendarRange className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input type="date" aria-label="Fecha desde" className="bg-white pl-9" value={fechaDesde} onChange={e=>setFechaDesde(e.target.value)}/></div><div className="relative"><CalendarRange className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input type="date" aria-label="Fecha hasta" className="bg-white pl-9" value={fechaHasta} min={fechaDesde||undefined} onChange={e=>setFechaHasta(e.target.value)}/></div></div>
 {cargando?<div className="grid gap-4 md:grid-cols-2"><div className="h-56 animate-pulse rounded-2xl bg-slate-200"/><div className="h-56 animate-pulse rounded-2xl bg-slate-200"/></div>:filtrados.length===0?<Card className="border-dashed shadow-none"><CardContent className="py-14 text-center"><h2 className="font-semibold">No hay avisos para mostrar</h2><p className="mt-2 text-sm text-slate-500">Creá tu primera oportunidad laboral o cambiá los filtros.</p></CardContent></Card>:<div className="grid gap-4 xl:grid-cols-2">{filtrados.map(a=><Card key={a.id} className="border-slate-200 shadow-sm"><CardContent className="p-6"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><Badge className={`border-0 ${tonos[a.estadoActual.codigoInterno]??tonos.BORRADOR}`}>{a.estadoActual.nombreEstadoAviso}</Badge><span className="text-xs text-slate-400">#{a.id}</span></div><h2 className="mt-3 truncate text-lg font-semibold">{a.nombreAviso}</h2><p className="mt-1 text-sm text-slate-500">{a.empresa.razonSocialEmpresa}</p></div><Menu aviso={a} session={session} onVer={()=>setVistaPrevia(a)} onAccion={accion} onCancelar={()=>setCancelar(a)}/></div><p className="mt-4 line-clamp-2 min-h-10 text-sm leading-5 text-slate-600">{a.descripcionAviso}</p><div className="mt-5 flex flex-wrap gap-4 border-t pt-4 text-xs text-slate-500"><span className="flex items-center gap-1.5"><CalendarDays className="h-3.5 w-3.5"/>Creado {formato.format(new Date(a.fechaCreacionAviso))}</span><span>Cierra {formato.format(new Date(a.fechaCierreAviso))}</span><span>{a.carreras.length} carreras</span></div></CardContent></Card>)}</div>}
 <Dialog open={Boolean(vistaPrevia)} onOpenChange={open=>!open&&setVistaPrevia(null)}><DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><div className="mb-2 flex items-center gap-2"><Badge className={`border-0 ${tonos[vistaPrevia?.estadoActual.codigoInterno??"BORRADOR"]}`}>{vistaPrevia?.estadoActual.nombreEstadoAviso}</Badge><span className="text-xs text-slate-400">Vista previa interna</span></div><DialogTitle className="text-2xl">{vistaPrevia?.nombreAviso}</DialogTitle><DialogDescription>{vistaPrevia?.empresa.razonSocialEmpresa}</DialogDescription></DialogHeader>{vistaPrevia&&<div className="space-y-6">{vistaPrevia.imagenUrlAviso?<div className="overflow-hidden rounded-xl border bg-slate-100"><img src={vistaPrevia.imagenUrlAviso} alt={`Portada de ${vistaPrevia.nombreAviso}`} className="max-h-72 w-full object-cover"/></div>:<div className="flex h-32 items-center justify-center rounded-xl border border-dashed bg-slate-50 text-sm text-slate-400">Este aviso no tiene imagen de portada</div>}<p className="whitespace-pre-wrap text-sm leading-6 text-slate-700">{vistaPrevia.descripcionAviso}</p><section><h3 className="mb-2 text-sm font-semibold">Carreras</h3><div className="flex flex-wrap gap-2">{vistaPrevia.carreras.map(c=><Badge key={c.id} variant="secondary">{c.nombreCarrera}</Badge>)}</div></section><section><h3 className="mb-2 text-sm font-semibold">Clasificación</h3><div className="space-y-2">{vistaPrevia.tiposAviso.map(t=><div key={t.id} className="rounded-lg border p-3 text-sm"><span className="font-medium">{t.nombreTipoAviso}:</span> <span className="text-slate-600">{t.subTiposAviso.map(s=>s.nombreSubTipoAviso).join(", ")||"Sin subtipo"}</span></div>)}</div></section><div className="flex flex-wrap gap-4 border-t pt-4 text-xs text-slate-500"><span>Creado {formato.format(new Date(vistaPrevia.fechaCreacionAviso))}</span><span>Cierra {formato.format(new Date(vistaPrevia.fechaCierreAviso))}</span></div></div>}</DialogContent></Dialog>
 <AlertDialog open={Boolean(cancelar)} onOpenChange={open=>!open&&setCancelar(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Cancelar aviso</AlertDialogTitle><AlertDialogDescription>El aviso “{cancelar?.nombreAviso}” dejará de estar disponible y esta acción no puede revertirse.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Volver</AlertDialogCancel><AlertDialogAction className="bg-rose-600 hover:bg-rose-700" onClick={()=>cancelar&&accion(cancelar,"cancelar")}>Cancelar aviso</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </ReclutadorShell>
}

function Menu({aviso,session,onVer,onAccion,onCancelar}:{aviso:AvisoGestion;session:AuthResponse;onVer:()=>void;onAccion:(a:AvisoGestion,n:"publicar"|"pausar"|"reanudar"|"cancelar")=>void;onCancelar:()=>void}) {
 const e=aviso.estadoActual.codigoInterno
 const puedeCancelar=["BORRADOR","ABIERTO","PAUSADO"].includes(e)&&session.permisos.includes("CANCELAR_AVISO")
 return <div className="flex items-center gap-1">
  {session.permisos.includes("VER_POSTULACIONES_AVISO")&&<Button asChild size="sm" variant="outline"><Link href={`/reclutador/avisos/${aviso.id}/postulaciones`}><Users className="mr-2 h-4 w-4"/>Postulaciones ({aviso.cantidadPostulaciones??0})</Link></Button>}
  <DropdownMenu><DropdownMenuTrigger asChild><Button size="icon" variant="ghost"><MoreHorizontal className="h-5 w-5"/><span className="sr-only">Acciones</span></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={onVer}><Eye className="mr-2 h-4 w-4"/>Vista previa</DropdownMenuItem>{e==="BORRADOR"&&session.permisos.includes("PUBLICAR_AVISO")&&<DropdownMenuItem onClick={()=>onAccion(aviso,"publicar")}><Play className="mr-2 h-4 w-4"/>Publicar</DropdownMenuItem>}{e==="ABIERTO"&&session.permisos.includes("PAUSAR_AVISO")&&<DropdownMenuItem onClick={()=>onAccion(aviso,"pausar")}><Pause className="mr-2 h-4 w-4"/>Pausar</DropdownMenuItem>}{e==="PAUSADO"&&session.permisos.includes("REANUDAR_AVISO")&&<DropdownMenuItem onClick={()=>onAccion(aviso,"reanudar")}><Play className="mr-2 h-4 w-4"/>Reanudar</DropdownMenuItem>}{puedeCancelar&&<DropdownMenuItem className="text-rose-600" onClick={onCancelar}><XCircle className="mr-2 h-4 w-4"/>Cancelar</DropdownMenuItem>}</DropdownMenuContent></DropdownMenu>
 </div>
}
